### ISSUE TITLE
can not connect to postgres

### ISSUE THREAD

**Issue by 4ss3g4f** [fametec/bacula#10]
`bacula-dir: dird.c:1279-0 postgresql.c:332 Unable to connect to PostgreSQL server. Database=bacula User=bacula`

**Comment by eduardofraga** [comment]
Bacula-director require the Catalog fametec/bacula-catalog, see docker-compose.yaml

**Comment by 4ss3g4f** [comment]
@eduardofraga , same error with fametec/bacula-catalog,

![image](https://user-images.githubusercontent.com/22811935/89422637-cd08ea80-d75f-11ea-8cd9-d16751e61dfa.png)

```
apiVersion: v1
kind: Service
metadata:
  name: catalog
spec:
  type: ClusterIP
  selector:
    app: bacula
    tier: catalog
  ports:
  - name: catalog
    protocol: TCP
    port: 5432
    targetPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: director
spec:
  type: ClusterIP
  selector:
    app: bacula
    tier: director
  ports:
  - name: director
    protocol: TCP
    port: 9101
    targetPort: 9101
---
apiVersion: v1
kind: Service
metadata:
  name: storage
spec:
  type: ClusterIP
  selector:
    app: bacula
    tier: storage
  ports:
  - name: storage
    protocol: TCP
    port: 9103
    targetPort: 9103
---
apiVersion: v1
kind: Service
metadata:
  name: client
spec:
  type: ClusterIP
  selector:
    app: bacula
    tier: client
  ports:
  - name: client
    protocol: TCP
    port: 9102
    targetPort: 9102
---
apiVersion: v1
kind: Service
metadata:
  name: baculum
spec:
  type: LoadBalancer
  selector:
    app: bacula
    tier: baculum
  ports:
  - name: name1
    port: 9095
    protocol: TCP
    targetPort: 9095
  - name: name2
    port: 9096
    protocol: TCP
    targetPort: 9096
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bacula
      tier: catalog
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: bacula
        tier: catalog
    spec:
      securityContext:
        runAsUser: 0
        fsGroup: 0
      volumes:
        - name: catalog
          persistentVolumeClaim:
            claimName: pvc-catalog
      restartPolicy: Always
      containers:
      - env:
        - name: POSTGRES_USER
          value: "bacula"
        - name: POSTGRES_PASSWORD
          value: "bacula"
        - name: POSTGRES_DB
          value: "bacula"
        image: fametec/bacula-catalog:9.6.5
        name: director
        ports:
        - name: catalog
          containerPort: 5432
        volumeMounts:
          - name: catalog
            mountPath: "/var/lib/postgresql/data"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: director
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bacula
      tier: director
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: bacula
        tier: director
    spec:
      securityContext:
        runAsUser: 0
        fsGroup: 0
      volumes:
        - name: bacula
          persistentVolumeClaim:
            claimName: pvc-bacula
      restartPolicy: Always
      containers:
      - image: fametec/bacula-director:9.6.5
        name: director
        ports:
        - name: director
          containerPort: 9101
        volumeMounts:
          - name: bacula
            mountPath: "/opt/bacula/etc"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: storage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bacula
      tier: storage
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: bacula
        tier: storage
    spec:
      securityContext:
        runAsUser: 0
        fsGroup: 0
      volumes:
        - name: bacula
          persistentVolumeClaim:
            claimName: pvc-bacula
      restartPolicy: Always
      containers:
      - image: fametec/bacula-storage:9.6.5
        name: storage
        ports:
        - name: storage
          containerPort: 9103
        volumeMounts:
          - name: bacula
            mountPath: "/opt/bacula/etc"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bacula
      tier: client
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: bacula
        tier: client
    spec:
      securityContext:
        runAsUser: 0
        fsGroup: 0
      volumes:
        - name: bacula
          persistentVolumeClaim:
            claimName: pvc-bacula
      restartPolicy: Always
      containers:
      - image: fametec/bacula-client:9.6.5
        name: client
        ports:
        - name: client
          containerPort: 9102
        volumeMounts:
          - name: bacula
            mountPath: "/opt/bacula/etc"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: baculum
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bacula
      tier: baculum
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: bacula
        tier: baculum
    spec:
      securityContext:
        runAsUser: 0
        fsGroup: 0
      volumes:
        - name: bacula
          persistentVolumeClaim:
            claimName: pvc-bacula
        - name: baculum
          persistentVolumeClaim:
            claimName: pvc-baculum
      restartPolicy: Always
      containers:
      - image: fametec/baculum:9.6.5
        name: baculum
        ports:
        - name: name1
          containerPort: 9095
        - name: name2
          containerPort: 9096
        volumeMounts:
          - name: bacula
            mountPath: "/opt/bacula/etc"
          - name: baculum
            mountPath: "/opt/bacula/etc/baculum"
```

**Comment by 4ss3g4f** [comment]
![image](https://user-images.githubusercontent.com/22811935/89477024-5e0ab080-d7b6-11ea-896a-a0d3f69ccc4f.png)

It's working properly with docker swarm, my yaml file:

```
x-bacula-depends-on: &bacula-depends-on
  depends_on:
    - db

version: '3.7'

networks:
  bridge:
    external: true

services:
  db:
    image: fametec/bacula-catalog:9.6.5
    networks:
      - bridge
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      POSTGRES_PASSWORD: bacula
      POSTGRES_USER: bacula
      POSTGRES_DB: bacula
    volumes:
      - /home/core/bacula/pgdata:/var/lib/postgresql/data:rw
    ports:
      - 5432:5432
  bacula-dir:
    <<: *bacula-depends-on
    image: assegaf/bacula-director:9.6.5
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    networks:
      - bridge
    volumes:
      - /home/core/bacula/etc/bacula-dir.conf:/opt/bacula/etc/bacula-dir.conf:ro
      - /home/core/bacula/etc/bconsole.conf:/opt/bacula/etc/bconsole.conf:ro
    ports:
      - 9101:9101
  storage:
    image: fametec/bacula-storage:9.6.5
    deploy:
      restart_policy:                                                   
        condition: on-failure                                           
        delay: 5s                                                       
        max_attempts: 3                                                 
        window: 120s
    networks:
      - bridge
    depends_on:
      - db
      - bacula-dir
    volumes:
      - /home/core/bacula/etc:/opt/bacula/etc:ro
    ports:
      - "9103:9103"
  client:
    image: fametec/bacula-client:9.6.5
    deploy:
      restart_policy:                                                   
        condition: on-failure                                           
        delay: 5s                                                       
        max_attempts: 3                                                 
        window: 120s
    networks:
      - bridge
    depends_on:
      - db
      - bacula-dir
      - storage
    volumes:
      - /home/core/bacula/etc:/opt/bacula/etc:ro
    ports:
      - "9102:9102"
  baculum:
    image: fametec/baculum:9.6.5
    deploy:
      restart_policy:                                                   
        condition: on-failure                                           
        delay: 5s                                                       
        max_attempts: 3                                                 
        window: 120s
    networks:
      - bridge
    depends_on:
      - db
      - bacula-dir
    volumes:
      - /home/core/bacula/etc:/opt/bacula/etc:ro
      - /home/core/bacula/etc/baculum:/opt/bacula/etc/baculum:rw
    ports:
      - "9095:9095"
      - "9096:9096"
```

What is the credential for baculum port 9095 ??

![image](https://user-images.githubusercontent.com/22811935/89477144-b346c200-d7b6-11ea-80d8-df4eacec2ec8.png)
